grails:
  google_maps_api_key: AIzaSyBYmHX5K2oKjw21DRwJp8LfL1ioTnDlIX8
  assetspath:
    path: /Applications/MAMP/htdocs/stockage/
    url: http://localhost:8884/stockage/
  serverUrl: http://localhost:8886
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.postgresql.Driver
  username: root
  password: root

environments:
  development:
    dbCreate: create-drop
    url: jdbc:postgresql://localhost:5432/devdbSadio
server:
  port: 8886